# Generated by Django 5.0 on 2023-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('MF_date', models.DateField()),
                ('product_no', models.CharField(max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app',
            },
        ),
    ]
